### ISSUE TITLE
Application code example?

### ISSUE THREAD

**Issue by foxdonut** [bredele/mood#8]
mood looks interesting, are there any code examples where it is used in an application?

**Comment by foxdonut** [comment]
@bredele ?

**Comment by bredele** [comment]
@foxdonut The [readme](https://github.com/bredele/mood/tree/master/test ) and the [test](https://github.com/bredele/mood/blob/master/test/mood.js) files are what you are looking for. Please let me know if you need more examples.

**Comment by foxdonut** [comment]
@bredele I saw those, and they do a great job of showing the API, which has gotten me interested because it looks good! However, what I'm looking of is an example of mood being used within an application, ideally giving a better sense of the problems that mood solves, rather than just unit-tests and discrete examples. I hope that makes sense. Are there any sample applications? Thanks in advance!

**Comment by foxdonut** [comment]
@bredele sorry to bother you, just a gentle ping :)

**Comment by foxdonut** [comment]
@bredele without seeing `mood` in a real application example, it's difficult to see the benefits that it brings vs writing the same application without it.

**Comment by foxdonut** [comment]
Oh well, looks like `mood` has been abandoned.

**Comment by foxdonut** [comment]
@bredele is `mood` being revived, or is it being sunset?

**Comment by bredele** [comment]
Hey @foxdonut I intend to maintain mood and it's not being sunset.

**Comment by foxdonut** [comment]
@bredele that is great to hear, thanks! Why was this issue "closed as completed" without providing any application examples? It would be very helpful to see the benefits that mood brings vs writing the same application without it.
